export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT'
export const AUTH_REFRESH = 'AUTH_REFRESH';
export const CLEAR_AUTH_REDIRECT = 'CLEAR_AUTH_REDIRECT';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const RESET_CLEAR_INPUT = 'RESET_CLEAR_INPUT';

export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const EXPAND_POST = 'EXPAND_POST';
